services:
  - type: web
    name: asignacion-salones
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        value: sqlite:///database.db
    plan: free